//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Checked {
            get {
                object obj = ResourceManager.GetObject("Checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 import vapoursynth as vs
        ///import sys
        ///from vapoursynth import core
        ///
        ///# Load source &amp; ripped files.
        ///srcpath = r&quot;%File1%&quot;
        ///rippath = r&quot;%File2%&quot;
        ///src = core.lsmas.LWLibavSource(srcpath)
        ///rip = core.lsmas.LWLibavSource(rippath)
        ///assert rip.format.color_family in [vs.YUV, vs.GRAY], &quot;only support YUV or Gray input&quot;
        ///
        ///def force8bit(clip):
        ///    if clip.format.bits_per_sample == 8:
        ///        return clip
        ///    return clip.resize.Spline64(format=clip.format.replace(bits_per_sample=8).id, dither_type=&apos;none&apos;)
        ///src = fo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 import vapoursynth as vs
        ///import sys
        ///from vapoursynth import core
        ///import muvsfunc as muf
        ///
        ///# Load source &amp; ripped files.
        ///srcpath = r&quot;%File1%&quot;
        ///rippath = r&quot;%File2%&quot;
        ///src = core.lsmas.LWLibavSource(srcpath)
        ///rip = core.lsmas.LWLibavSource(rippath)
        ///assert rip.format.color_family in [vs.YUV, vs.GRAY], &quot;only support YUV or Gray input&quot;
        ///
        ///def force8bit(clip):
        ///    if clip.format.bits_per_sample == 8:
        ///        return clip
        ///    return clip.resize.Spline64(format=clip.format.replace(bits_per_sample=8).id, dithe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GMSD {
            get {
                return ResourceManager.GetString("GMSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Unchecked {
            get {
                object obj = ResourceManager.GetObject("Unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
